apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-alerts
    receivers:
      - uid: discord-webhook
        type: discord
        settings:
          url: https://discord.com/api/webhooks/1460302915687415972/-rnBAqFe1DaoH3DjDKzBDcqhA2RIFzfab7CcfHQoMDOL8RIT7Iozo2r65Mk-d0GUmLw1
          title: "Alerte Steam Update"
          message: |
            **{{ .Status | toUpper }}**
            {{ range .Alerts }}
            **{{ .Labels.alertname }}**
            {{ .Annotations.description }}
            {{ end }}
        disableResolveMessage: true
